version: "3"

services:
  smartmet-server:
    # cap_add:
    #   - SYS_PTRACE
    image: smartmet-grid:latest
    build: 
      context: ./
      dockerfile: smartmet-server.Dockerfile
    container_name: smartmet-server
    volumes:
      - ./smartmet:/etc/smartmet:Z
      - ../era5-data/:/srv/data:ro
      - ./scripts:/srv/scripts:Z
    environment:
      # Settings for grib files are here
      - SMARTMET_GRID_CONFIG_FILE=/etc/smartmet/libraries/grid-files/grid-files.conf
      # Other settings for grib file things
      - SMARTMET_ENV_FILE=/etc/smartmet/engines/grid-engine/base.conf
      # Redis adderess is the name of docker service
      - REDIS_CONTENT_SERVER_ADDRESS=redis-db
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=a.
      - POSTGRES_PASSWORD=OmaHassuSalasana1234!
    ports:
      - "80:8080"
    depends_on: 
      - fminames-db
      - redis-db
    restart: always
    entrypoint: 
      - "/srv/scripts/wait-for-postgres.sh"
    command: fminames-db /usr/sbin/smartmetd -c /etc/smartmet/smartmet.conf

  # Smartmet-server is very demanding and requires this database to be present
  fminames-db:
    build: 
      context: ./
      dockerfile: fminames-db.Dockerfile
    image: fminames-db:latest
    container_name: smartmet-grid-postgresql-db
    restart: "no"
    environment:
      # This silly password needs to copied into ./smartmet/geonames.conf
      - POSTGRES_PASSWORD=OmaHassuSalasana1234!
      - POSTGRES_USER=fminames_user
      # POSTGRES_DB: fminames  
    ports:
      # Port exposed for connecting from host (not required in production)
     - "5432:5432"
    volumes:
      # Keep database stuff stored on local file system
      - db:/var/lib/postgresql/data


  # Redis is used for storing information for grib-data files
  redis-db:
    # From image...
    image: redis:latest
    # Create a container named...
    container_name: redis-content-server
    restart: always
    ports:
      # Port exposed for connecting from host (not required in production)
      - "6379:6379"

volumes:
  db:
